[project]
name = "data-cleaning-for-housing-data"
version = "0.1.0"
description = "Cleaning the *Nashville Housing Data* dataset."
authors = [
    {name = "Giorgia Faedda",email = "giorgiafaedda3@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "sqlalchemy (>=2.0.39,<3.0.0)",
    "psycopg2 (>=2.9.10,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "scripts" },
]

[tool.poe.tasks]
remove-bom = "python ./scripts/remove_bom.py --input='./data/dataset.csv' --output='./data/dataset_no_bom.csv'"
load-csv = "python ./scripts/load_csv.py --host=localhost --username=postgres --dbname=postgres --port=5433 --dataset='./data/dataset_no_bom.csv' --tablename='HousingDataRaw'"
ensure-out-dir = "python -c \"import os; os.makedirs('directory/path', exist_ok=True)\""
sql-install-fuzzystrmatch = "psql --host=localhost --username=postgres --dbname=postgres --port=5433 -c \"CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;\""
slq-cleanup = "psql --host=localhost --username=postgres --dbname=postgres --port=5433 -f ./src/cleaning.sql"
data-cleaning-pipeline = [
  "ensure-out-dir", 
  "remove-bom", 
  "load-csv", 
  "sql-install-fuzzystrmatch", 
  "slq-cleanup", 
  ]

