[project]
name = "data-cleaning-for-housing-data"
version = "0.1.0"
description = "Cleaning the *Nashville Housing Data* dataset."
authors = [
    {name = "Giorgia Faedda",email = "giorgiafaedda3@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "sqlalchemy (>=2.0.39,<3.0.0)",
    "psycopg2 (>=2.9.10,<3.0.0)",
    "folium (>=0.19.5,<0.20.0)",
    "python-dotenv (>=1.0.1,<2.0.0)"
]

[tool.poetry.requires-plugins]
poethepoet = { version = "~0.34.0", extras = ["poetry_plugin"] }

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "scripts" },
]

[tool.poe.tasks]
remove-bom = "python ./scripts/remove_bom.py --input='./data/dataset.csv' --output='./data/dataset_no_bom.csv'"
load-csv = "python ./scripts/load_csv.py --datasetFile='./data/dataset_no_bom.csv' --table='HousingDataRaw'"
ensure-out-dir = "python -c \"import os; os.makedirs('out', exist_ok=True)\""
sql-install-fuzzystrmatch = "python ./scripts/psql_with_config.py -c \"CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;\""
sql-cleanup = "python ./scripts/psql_with_config.py -f ./src/cleaning.sql"
data-cleaning-pipeline = [
  "ensure-out-dir", 
  "remove-bom", 
  "load-csv",
  "sql-install-fuzzystrmatch", 
  "sql-cleanup", 
]
